services:
    sebk_small_orm_connection:
        class: Sebk\SmallOrmBundle\Database\Connection
        arguments: [%database_type%, %database_host%, %database_name%, %database_user%, %database_password%]