services:
    sebk_small_orm_connections:
        class: Sebk\SmallOrmBundle\Factory\Connections
        arguments: [%sebk_small_orm.connexions%, %sebk_small_orm.default_connection%]
    sebk_small_orm_dao:
        class: Sebk\SmallOrmBundle\Factory\Dao
        arguments: [@sebk_small_orm_connections, %sebk_small_orm.bundles%]